name: Build campaign module

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/module-campaigns/Dockerfile
          push: false