name: Build campaign module

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build campaigns module
        working-directory: backend
        run: docker build -f ./module-campaigns/Dockerfile .